
[game]
name = "Dino Crisis 2"
id = "SLUS-01279"
players = 1
exe = "disc/SLUS_012.79"
disc = "disc/Dino Crisis 2 (USA).cue"
discs = ["disc/Dino Crisis 2 (USA).cue"]
disc_serials = ["SLUS-01279"]
load_address = "0x80018000"
entry_pc = "0x8001B3B8"
text_size = "0x00090000"
stack_base = "0x801FFFF0"

[prepare_disc]
out_dir = "disc"
bin_name = "Dino Crisis 2 (USA) (Track 1).bin"
cue_name = "Dino Crisis 2 (USA).cue"
boot_exe = "SLUS_012.79"
known_sizes = [473676336, 511073136]
known_md5 = ["fc8cc9fc5ed761ed5d9cf025df7a6877", "90aff14adec53fbe0fb8d3725debdde3"]
known_sha1 = ["f7c71427c4c8726c9114514746c42f10928fbaee", "8c4214caa6744a2b248afe1b93f71ee22ce19343"]
known_crc32 = ["47435b81", "cb99fb35"]

[recompiler]
bios_config = "psxrecomp/bios/SCPH1001.toml"
seeds = "seeds/ghidra_funcs.txt"
out_dir = "generated"
strict = true

[runtime]
window_title = "Dino Crisis 2 Recompiled"
memcard_dir = "saves"
bios_hle = false
openbios = false
overlay_cache = true

[video]
renderer = "opengl"
aspect_ratio = "4:3"

[controller]
default_mode = "digital"

[netplay]
require_cue = true
required_tracks = 2
required_disc_fp = "968b6f2f81c9cbb2bf212d3f28f0ffb585ac156985bbb015bebf20a94b30ff55"
